create table metodo_pagamento
(
    id        bigint generated by default as identity,
    descricao varchar(255),
    primary key (id)
);
create table pagamento
(
    id bigint generated by default as identity,
    cod_debito          integer not null ,
    cpf_cnpj            varchar(255) not null ,
    id_metodo_pagamento bigint not null ,
    num_cartao          varchar(255),
    valor_pagamento     numeric(38, 2) not null ,
    status_pagamento    tinyint check (status_pagamento between 0 and 2) not null,
    primary key (id)
);
alter table if exists pagamento
    add constraint FK31fc7rfjg5g8s5k9r9k6oyuap
    foreign key (id_metodo_pagamento)
    references metodo_pagamento

